DELETE FROM notification_templates
WHERE event_type IN ('CHORE_DUE_SOON', 'CHORE_DUE_NOW', 'CHORE_OVERDUE')
  AND style IN ('NORMAL', 'FUNNY', 'MOTIVATIONAL', 'COMPETITIVE', 'MINIMAL');

INSERT INTO notification_templates (event_type, style, title_template, message_template, enabled)
VALUES
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} is coming up and is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Reminder: {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} is scheduled for {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'You have an upcoming chore: {chore_name}, due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} is due soon at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Upcoming task: {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Your {chore_name} reminder is here. It is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} is approaching its due time of {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Plan ahead for {chore_name}, due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} is still pending and due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Just a reminder that {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} is next on your chore list and is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Your upcoming {chore_name} task is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', '{chore_name} needs attention by {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'NORMAL', 'Chore due soon', 'Reminder for later: {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. It has started checking the clock.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. Future you has requested backup.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. It has noticed you looking the other way.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. It has been very patient about this.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Friendly warning: {chore_name} is approaching with suspicious confidence.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. It has already cleared its schedule for you.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. Your couch says it will keep your spot.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. Your excuses have been placed on standby.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Forecast for {due_time}: a strong chance of {chore_name}.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. The cleaning supplies are trying not to make eye contact.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. Please enjoy your remaining minutes of pretending it does not exist.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. It promises this will only be slightly inconvenient.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'The household calendar would like to remind you that {chore_name} exists. Rude, but accurate.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. No rush. Actually, a little rush.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. The task is pretending not to stare.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. The house would like a tiny favor.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Your regularly scheduled encounter with {chore_name} is approaching.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. The household has begun pretending not to notice.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. The household atmosphere has become suspiciously productive.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. Your couch has declined to comment.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. Snacks may improve morale.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is approaching. Future you would like present you to handle this one.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Just a heads-up: {chore_name} is getting closer, unlike your motivation.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is almost here. Your free time has been notified.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. It would really prefer not to become tomorrow''s problem.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. Even the dust looks nervous.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} has reserved {due_time} under the name ''things we cannot ignore forever.''', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is approaching. Consider this the polite version of the reminder.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'At {due_time}, {chore_name} would appreciate a brief appearance from its assigned human.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. The reminder was told to be nice this time.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Coming soon to a household near you: {chore_name}.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is in the waiting room. It brought a magazine and everything.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. You still have time to make it look intentional.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. Your procrastination department has been notified.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. The household has faith in you. Mostly.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. This is your chance to look suspiciously responsible.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. It would like to avoid sending a follow-up.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. It has requested five minutes of your attention and possibly several more.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Your future self sent a message: ''Please do {chore_name} before I have to.''', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is approaching. Your motivation has also been invited.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. Your future self is watching this decision closely.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. The procrastination window is closing gently.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is coming up. The mess has been informed.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', 'Small domestic alert: {chore_name} is coming up.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} has joined your upcoming schedule without asking permission.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. Please say goodbye to a few peaceful minutes.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is approaching. It is trying very hard not to look impatient.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due at {due_time}. It expects a brief visit from you.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is due soon. Congratulations, the household picked you.', TRUE),
    ('CHORE_DUE_SOON', 'FUNNY', 'Chore due soon', '{chore_name} is almost here. Please begin negotiations with your motivation.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is due at {due_time}. A little progress now can make later much easier.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'You have time to get ahead on {chore_name} before {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is coming up. One focused effort can get it off your mind.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'Take care of {chore_name} before {due_time} and give yourself one less thing to think about.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is due soon. You can knock this out and keep the momentum going.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'Small tasks add up to a better space. {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'Get a head start on {chore_name}. Future you will appreciate it.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is coming up. Start when you are ready and make it an easy win.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'You are one completed {chore_name} away from a cleaner slate.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is due at {due_time}. A few focused minutes can make a real difference.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'Keep your rhythm going. {chore_name} is the next step.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is due soon. Handle it early and enjoy the win.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'This is your chance to get ahead. {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', 'One task at a time. {chore_name} is coming up next.', TRUE),
    ('CHORE_DUE_SOON', 'MOTIVATIONAL', 'Chore due soon', '{chore_name} is due soon. Start small, finish strong.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is due at {due_time}. Beat the clock and put a point on the board early.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is coming up. Get it done before the deadline and stay ahead.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'The next round is {chore_name}. Finish before {due_time} and claim the early win.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is due soon. Time to make the scoreboard nervous.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'Race the clock: {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is your next chance to gain ground before the deadline.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'Get {chore_name} done early and set the pace for the household.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is approaching. First move advantage is yours.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'Another round is coming up. {chore_name} is due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'Put {chore_name} away before the buzzer and keep your momentum.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is due soon. A clean finish beats a last-minute scramble.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'Your next challenge is {chore_name}. Deadline: {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is on deck. Get ahead before the clock catches up.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', 'Turn {chore_name} into an early victory before {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'COMPETITIVE', 'Chore due soon', '{chore_name} is coming up. Stay sharp, stay ahead.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} due at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Upcoming: {chore_name}, {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} is due soon.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Reminder: {chore_name} at {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} coming up.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Due soon: {chore_name}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name}, due {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Next chore: {chore_name}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} is next.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Upcoming chore: {chore_name}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} needs attention soon.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} deadline: {due_time}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Plan for {chore_name}.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', '{chore_name} is approaching.', TRUE),
    ('CHORE_DUE_SOON', 'MINIMAL', 'Chore due soon', 'Reminder set: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} is due now.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'It is time for {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} has reached its due time.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'Your {chore_name} task is due now.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} is ready to be completed.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'Reminder: {chore_name} is due now.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} is scheduled for now.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'Your scheduled time for {chore_name} has arrived.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} needs attention now.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'The due time for {chore_name} is here.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} is currently due.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'Now due: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'It is time to take care of {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', '{chore_name} is due and still pending.', TRUE),
    ('CHORE_DUE_NOW', 'NORMAL', 'Chore due now', 'Your chore {chore_name} is due now.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'Breaking news: {chore_name} has entered the chat.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It has officially stopped being a future problem.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It is standing there like you forgot an appointment.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It has been very patient.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'The clock has spoken. Unfortunately, it said ''{chore_name}.''', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is officially due. Your couch has been informed of the temporary separation.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'Plot twist: the moment for {chore_name} is now.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} has left the waiting room and would like to see you now.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. The house has noticed.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. This would be a great time to suddenly become productive.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. The countdown is over and the chore looks pleased with itself.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Please report to the nearest ounce of responsibility.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'Your chore alarm is ringing, except the alarm is this sentence.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} has arrived right on time, which is honestly a little smug.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Your cleaning supplies are waiting awkwardly.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'The deadline has arrived. {chore_name} would like a word.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} just became a present-tense problem.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Admission is free. Participation is less optional.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It would really like to stop appearing in notifications.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'The clock hit {due_time}. {chore_name} immediately took that personally.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due. Your couch says goodbye for now.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Your motivation has been paged.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} has officially moved from ''later'' to ''well, now.''', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Procrastination has requested an extension and been denied.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Refreshing the page will not change that.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. The task is looking directly at you.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'Time for {chore_name}. It has waited long enough to become confident.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. One small unit of effort should do nicely.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'The deadline is here. {chore_name} has brought witnesses.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Whatever is involved would very much like some closure.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Congratulations on today''s least surprising surprise.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. No premium membership can remove it.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It is requesting your immediate attention. Politely, for now.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due. This is the part where you mysteriously become responsible.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'Your appointment with {chore_name} has begun. Reception says you are right on time-ish.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It has had enough time to learn your routine.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It has moved itself to the top of the imaginary list.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Please remain calm and locate some motivation.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'The deadline is now. {chore_name} has stopped sending polite calendar invites.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due. The procrastination trial period has expired.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Unfortunately, room service is not handling this one.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. The household requests one small contribution.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'The timer says now. {chore_name} says also now. Very coordinated.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. The house is asking nicely.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Time to make the mess slightly less confident.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Reward: not having to think about {chore_name} anymore.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due. The chore department would like to close this ticket.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. It is currently accepting applications for someone to finish it.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', '{chore_name} is due now. Future you is already hoping this goes well.', TRUE),
    ('CHORE_DUE_NOW', 'FUNNY', 'Chore due now', 'Time for {chore_name}. Let''s settle this peacefully before it becomes a sequel.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is due now. Start with one small step and build from there.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'This is your moment to finish {chore_name} and clear some mental space.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is due now. You can handle this.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'Take a few focused minutes for {chore_name} and turn it into a completed win.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is ready. Start now and let momentum do the rest.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'One task, one finish. It is time for {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is due now. Getting started is the hardest part, and you can do that.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'Give {chore_name} your focus now, then enjoy having it behind you.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'This is a good moment to take care of {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is due now. Make the space better one task at a time.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'You have got this. {chore_name} is the only target right now.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'Start {chore_name}, keep it simple, and finish strong.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is due. Turn this reminder into a small win.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', 'Take action on {chore_name} now and keep your momentum alive.', TRUE),
    ('CHORE_DUE_NOW', 'MOTIVATIONAL', 'Chore due now', '{chore_name} is ready to be crossed off. Go claim that feeling.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is due now. Beat the clock and close the round.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'Game time: {chore_name}. Put the point on the board.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is live. Finish strong and keep your edge.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'The timer has hit zero. Now win the {chore_name} round.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is due. Time to turn pending into completed.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'Your next point is sitting inside {chore_name}. Go get it.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is due now. Make the scoreboard move.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'The round starts now: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is up. Finish it before the momentum disappears.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'Time to convert {chore_name} into a clean win.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is due. Stay ahead by finishing what is in front of you.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'Your current challenge: {chore_name}. Finish and move on.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is on the clock. Close it out.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', 'Make {chore_name} your next completed objective.', TRUE),
    ('CHORE_DUE_NOW', 'COMPETITIVE', 'Chore due now', '{chore_name} is due now. One task, one point, one win.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name} is due now.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Due now: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Time for {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name}: now due.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Do {chore_name} now.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name} is ready.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Now: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name} needs attention.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Current chore: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name} deadline reached.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Start {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name} is pending.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Task due: {chore_name}.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', '{chore_name}, due now.', TRUE),
    ('CHORE_DUE_NOW', 'MINIMAL', 'Chore due now', 'Next action: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} is overdue.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} is still pending and overdue.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', 'Reminder: {chore_name} is overdue.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} is now {hours_late}h overdue.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', 'Your {chore_name} task has passed its due time.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} remains incomplete after its due time.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', 'Overdue task: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} still needs to be completed.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} is past due and still pending.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', 'Please complete {chore_name} when you can.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} has not yet been completed and is overdue.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', 'Your overdue chore {chore_name} is still open.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} is {hours_late}h past its scheduled time.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', '{chore_name} needs attention because its due time has passed.', TRUE),
    ('CHORE_OVERDUE', 'NORMAL', 'Chore overdue', 'Reminder: {chore_name} remains overdue.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been waiting so long it started questioning its purpose 🧽', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', 'Breaking news: {chore_name} is still there. More at eleven.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been overdue for {hours_late}h and is beginning to feel like part of the furniture.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. It has started taking this personally.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', 'The deadline left {hours_late}h ago. {chore_name} did not.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. It has started writing a strongly worded email.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still waiting. Honestly, the commitment is impressive.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been overdue for {hours_late}h. It has started checking the clock.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} would like to remind everyone that it has not, in fact, completed itself.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. The task has requested a manager.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still pending and has begun exploring long-term housing options.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. Somewhere, the household just sighed dramatically.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been waiting so long it now has seniority.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still waiting patiently. It deserves employee of the month at this point 🏆', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still unfinished. At this point, even it seems surprised.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has crossed from ''task'' into ''ongoing storyline.''', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. The suspense is becoming unnecessary.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been overdue for {hours_late}h and would like closure.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still there. Bold strategy from the chore.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', 'The deadline left a while ago. {chore_name} is still hanging around.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. Your future self has opened a support ticket.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. It is getting a little too comfortable here.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. The chore department has escalated the case to ''please?''', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still pending. It has had plenty of time to think about what happened.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. It has started making itself at home.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been overdue for {hours_late}h. It knows what you did. Or rather, did not do.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still waiting. At this point, it knows the Wi-Fi password.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. Procrastination is having an excellent day.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} missed its deadline and is now following you around as a guilt trip.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. This sequel did not need to happen.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still unfinished. Honestly, the persistence is impressive.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. The household calendar has begun tapping its watch.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been overdue for {hours_late}h. Even the calendar is getting impatient.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still waiting. It has had enough time to start a support group.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. It is slowly becoming part of the décor.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been waiting long enough to qualify for loyalty points.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. Please finish it before it starts asking for its own shelf.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still here. It has achieved remarkable job security.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. The chore has entered the ''we need to talk'' phase.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been overdue for {hours_late}h. Even the reminder is getting tired.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still pending. It has begun making itself comfortable.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. Apparently, the person assigned to fix this situation is you.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has outlived its deadline. Impressive, but not ideal.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. It is now less of a reminder and more of a roommate.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} has been waiting for {hours_late}h past due. It brought snacks.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still open. The chore has declined all requests to disappear magically.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. Your calendar is trying very hard not to say ''I told you so.''', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still pending. Future you is not impressed.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is overdue. The house would like to know your plan.', TRUE),
    ('CHORE_OVERDUE', 'FUNNY', 'Chore overdue', '{chore_name} is still waiting. Let''s finish it before it gets too attached.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', '{chore_name} is overdue, but the best time to restart is now.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'No need to dwell on the missed deadline. Take the next step on {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', '{chore_name} is overdue. Finish it now and give yourself a fresh start.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'You can still turn {chore_name} into a win. Start with one small action.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', '{chore_name} is still open. Progress now matters more than the delay.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'Reset the momentum by taking care of {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', '{chore_name} is overdue, but it is absolutely still manageable.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'One focused push can put {chore_name} behind you.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'Do not worry about being late. Focus on finishing {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', '{chore_name} is overdue. Clear it now and move forward lighter.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'The deadline passed, but your chance to finish strong did not.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'Take back control of the list. {chore_name} is a good place to start.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', '{chore_name} is still waiting. You can close it out today.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'A delayed task is still a finishable task. Start {chore_name} now.', TRUE),
    ('CHORE_OVERDUE', 'MOTIVATIONAL', 'Chore overdue', 'Turn the overdue reminder into a comeback. Finish {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is overdue. Comeback round starts now.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'The clock got the first point. Take the next one by finishing {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is still open. Time to turn the score around.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'Overdue does not mean defeated. Close out {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is behind schedule. Make this the comeback play.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'The deadline won the first round. Finish {chore_name} and answer back.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is overdue. Stop the clock from running up the score.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'Your next comeback point is {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is still pending. Finish it and get back in the race.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'Make up ground by closing {chore_name} now.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is overdue. One completion puts momentum back on your side.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'The round is not over until {chore_name} is done.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} slipped past the deadline. Take the win back.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', 'Turn {chore_name} from overdue into completed and keep moving.', TRUE),
    ('CHORE_OVERDUE', 'COMPETITIVE', 'Chore overdue', '{chore_name} is your comeback challenge. Finish strong.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name} is overdue.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Overdue: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name} still pending.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name}: {hours_late}h overdue.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Past due: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Finish {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name} needs attention.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Pending overdue: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name} remains open.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Late task: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name} passed its deadline.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Complete {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name} is still due.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', 'Overdue chore: {chore_name}.', TRUE),
    ('CHORE_OVERDUE', 'MINIMAL', 'Chore overdue', '{chore_name}, still unfinished.', TRUE);
