spring:
  config:
    activate:
      on-profile: local

app:
  security:
    session-cookie-secure: ${SESSION_COOKIE_SECURE:false}

server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:false}